name: umeng_analytics_plugin_example
description: Demonstrates how to use the umeng_analytics_plugin plugin.
version: 1.0.3
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  umeng_analytics_plugin:
    path: ../

flutter:
  uses-material-design: true
